In [45]:
import pandas as pd
import numpy as np
import json
from us import states

In [3]:
population = pd.read_csv(open('congressional_district_population.csv'))

In [4]:
population

,District,Urban,Suburban,Rural,Urban %,Suburban %,Rural %,Most Prevalent
0,U.S.A.,"83,171,109","169,710,405","68,122,772",25.9,52.9,21.2,Suburban
1,Alabama,"967,111","2,004,018","1,879,647",19.9,41.3,38.7,Suburban
2,AL-01,"148,964","302,147","255,481",21.1,42.8,36.2,Suburban
3,AL-02,"146,722","253,542","281,148",21.5,37.2,41.3,Rural
4,AL-03,"118,205","273,994","316,656",16.7,38.7,44.7,Rural
...,...,...,...,...,...,...,...,...
483,WI-06,"111,041","371,196","230,104",15.6,52.1,32.3,Suburban
484,WI-07,"93,645","176,870","433,122",13.3,25.1,61.6,Rural
485,WI-08,"141,782","312,855","272,676",19.5,43.0,37.5,Suburban
486,Wyoming,"105,583","257,596","220,020",18.1,44.2,37.7,Suburban
487,WY-AL,"105,583","257,596","220,020",18.1,44.2,37.7,Suburban

In [34]:
state_list = []
states2abbr = dict()
for state in states.STATES:
    state_list.append(state.name)
    states2abbr[state.name] = state.abbr

In [27]:
state_pops = population[population['District'].isin(state_list)].reset_index(drop=True)

In [60]:
def clean_states(in_df):
    df = in_df.copy()
    df = df.rename(columns={'District': 'state_po', 'Urban': 'urban', 'Suburban': 'suburban', 'Rural': 'rural', 
                            'Urban %': 'urban_pct', 'Suburban %': 'suburban_pct',
                            'Rural %': 'rural_pct', 'Most Prevalent': 'prevalent'})
    df['urban_pct'] /= 100
    df['suburban_pct'] /= 100
    df['rural_pct'] /= 100
    df['state_po'] = list(map(lambda x: states2abbr[x], state_pops['District']))
    df['prevalent'] = (df['prevalent']).str.lower()
    return df

In [61]:
clean_states(state_pops)

,state_po,urban,suburban,rural,urban_pct,suburban_pct,rural_pct,prevalent
0,AL,"967,111","2,004,018","1,879,647",0.199,0.413,0.387,suburban
1,AK,"162,281","367,243","209,041",0.220,0.497,0.283,suburban
2,AZ,"1,859,473","4,038,989","911,472",0.273,0.593,0.134,suburban
3,AR,"596,803","1,116,106","1,265,033",0.200,0.375,0.425,rural
4,CA,"12,792,442","23,249,186","2,941,224",0.328,0.596,0.075,suburban
5,CO,"1,251,318","3,371,242","813,959",0.230,0.620,0.150,suburban
6,CT,"780,783","2,287,459","526,232",0.217,0.636,0.146,suburban
7,DE,"158,557","576,003","209,169",0.168,0.610,0.222,suburban
8,FL,"4,820,072","12,937,010","2,521,349",0.238,0.638,0.124,suburban
9,GA,"1,745,555","5,703,741","2,752,349",0.171,0.559,0.270,suburban
10,HI,"383,538","804,884","233,234",0.270,0.566,0.164,suburban
11,ID,"256,176","818,391","582,804",0.155,0.494,0.352,suburban
12,IL,"4,201,702","6,835,790","1,817,022",0.327,0.532,0.141,suburban
13,IN,"1,533,361","3,067,214","2,013,826",0.232,0.464,0.304,suburban
14,IA,"766,896","1,321,059","1,030,152",0.246,0.424,0.330,suburban
15,KS,"717,149","1,457,437","729,232",0.247,0.502,0.251,suburban
16,KY,"768,993","1,814,355","1,841,030",0.174,0.410,0.416,rural
17,LA,"1,122,936","1,870,107","1,670,417",0.241,0.401,0.358,suburban
18,ME,"169,159","439,217","721,791",0.127,0.330,0.543,rural
19,MD,"1,319,786","3,851,529","824,763",0.220,0.642,0.138,suburban
20,MA,"2,038,547","4,008,444","742,258",0.300,0.590,0.109,suburban
21,MI,"2,105,789","4,984,421","2,835,365",0.212,0.502,0.286,suburban
22,MN,"1,221,629","2,908,389","1,360,699",0.222,0.530,0.248,suburban
23,MS,"573,197","948,145","1,464,890",0.192,0.318,0.491,rural
24,MO,"1,327,209","2,894,452","1,853,653",0.218,0.476,0.305,suburban
25,MT,"206,990","374,725","448,148",0.201,0.364,0.435,rural
26,NE,"528,917","885,940","479,063",0.279,0.468,0.253,suburban
27,NV,"851,093","1,807,370","229,254",0.295,0.626,0.079,suburban
28,NH,"172,183","588,579","571,091",0.129,0.442,0.429,suburban
29,NJ,"2,122,120","6,127,049","711,005",0.237,0.684,0.079,suburban
30,NM,"588,003","882,881","613,941",0.282,0.423,0.294,suburban
31,NY,"8,949,617","8,215,936","2,632,666",0.452,0.415,0.133,urban
32,NC,"1,743,246","4,723,295","3,586,030",0.173,0.470,0.357,suburban
33,ND,"137,364","360,214","247,898",0.184,0.483,0.333,suburban
34,OH,"2,781,876","6,042,368","2,785,506",0.240,0.520,0.240,suburban
35,OK,"910,823","1,746,682","1,238,750",0.234,0.448,0.318,suburban
36,OR,"945,581","2,170,700","908,859",0.235,0.539,0.226,suburban
37,PA,"3,254,638","6,181,922","3,353,932",0.254,0.483,0.262,suburban
38,RI,"329,864","601,320","124,952",0.312,0.569,0.118,suburban
39,SC,"724,890","2,368,955","1,799,607",0.148,0.484,0.368,suburban
40,SD,"177,858","335,251","342,337",0.208,0.392,0.400,rural
41,TN,"1,406,166","2,832,879","2,358,326",0.213,0.429,0.357,suburban
42,TX,"7,470,245","15,296,734","4,652,627",0.272,0.558,0.170,suburban
43,UT,"587,860","1,957,121","448,959",0.196,0.654,0.150,suburban
44,VT,"81,200","168,680","374,757",0.130,0.270,0.600,rural
45,VA,"1,582,974","4,712,085","2,070,882",0.189,0.563,0.248,suburban
46,WA,"1,585,521","4,172,702","1,411,746",0.221,0.582,0.197,suburban
47,WV,"252,791","549,452","1,034,598",0.138,0.299,0.563,rural
48,WI,"1,422,944","2,615,066","1,725,191",0.247,0.454,0.299,suburban
49,WY,"105,583","257,596","220,020",0.181,0.442,0.377,suburban

['AL',
 'AK',
 'AZ',
 'AR',
 'CA',
 'CO',
 'CT',
 'DE',
 'FL',
 'GA',
 'HI',
 'ID',
 'IL',
 'IN',
 'IA',
 'KS',
 'KY',
 'LA',
 'ME',
 'MD',
 'MA',
 'MI',
 'MN',
 'MS',
 'MO',
 'MT',
 'NE',
 'NV',
 'NH',
 'NJ',
 'NM',
 'NY',
 'NC',
 'ND',
 'OH',
 'OK',
 'OR',
 'PA',
 'RI',
 'SC',
 'SD',
 'TN',
 'TX',
 'UT',
 'VT',
 'VA',
 'WA',
 'WV',
 'WI',
 'WY']